//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpCamera.Finder.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI_main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI_main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpCamera.Finder.Test.UI_main", typeof(UI_main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Cameras.
        /// </summary>
        internal static string btnDetectCameras {
            get {
                return ResourceManager.GetString("btnDetectCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Camera Information.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Plan.
        /// </summary>
        internal static string btnLoadPlan {
            get {
                return ResourceManager.GetString("btnLoadPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Picture.
        /// </summary>
        internal static string btnTakePicture {
            get {
                return ResourceManager.GetString("btnTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a camera....
        /// </summary>
        internal static string cbCameras {
            get {
                return ResourceManager.GetString("cbCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Plan.
        /// </summary>
        internal static string hidePlan {
            get {
                return ResourceManager.GetString("hidePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Plan.
        /// </summary>
        internal static string showPlan {
            get {
                return ResourceManager.GetString("showPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Information.
        /// </summary>
        internal static string stcCameraInfo {
            get {
                return ResourceManager.GetString("stcCameraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desctiption.
        /// </summary>
        internal static string stcDescription {
            get {
                return ResourceManager.GetString("stcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string stcIP {
            get {
                return ResourceManager.GetString("stcIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string stcModel {
            get {
                return ResourceManager.GetString("stcModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string stcResolution {
            get {
                return ResourceManager.GetString("stcResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Cameras.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
